baseurl = "https://tristor.ro/"
languageCode = "en-us"
theme = "blackburn"
title = "Wandering in Wondering"
author = "Tristor"
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[permalinks]
  post = "/blog/:year/:month/:day/:title/"
  page = "/:filename/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Code, Coffee, Photography, and Travel"
  brand = "Wandering<br>in<br>Wondering"
  googleAnalytics = "UA-74523510-1"
  disqus = "wanderinginwondering"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topic"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Resume"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "resume"
    url = "/resume/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  flickr = "totaledcow"
  twitter = "tristor"
  github = "tristor"
  linkedin = "tylerduzan"
  hackernews = "tristor"
  reddit = "tristor"
